### ISSUE TITLE
Feature request: Searching for Trusts

### ISSUE THREAD

**Issue by danielburnley** [DFE-Digital/sdd-technical-documentation#1]
## Context

For the Academy Transfers project user research has shown that users search for trusts using one of three bits of information:

- The 'Trust reference number'
- The name of the trust
- The companies house number

For usability we've combined these searches into one input as shown here:
![image](https://user-images.githubusercontent.com/976254/111166078-a9304180-8597-11eb-99d0-cea768b309ae.png)

### General

This request should be paginated

### Request

An endpoint that allows us to search by:

- The 'Trust reference number'
- The name of the trust
- The companies house number

Ideally, being able to search against all three at once using our single input would help with development and reduce the number of requests made to the API

### Response

An array of the matching trusts

**Comment by StevenLeighton21** [comment]
Now in the updated contract specification as requested
